### ISSUE TITLE
Trainning error

### ISSUE THREAD

**Issue by deep-practice** [msed-Ebrahimi/ARoFace#2]
Traceback (most recent call last):
  File "train_v2.py", line 267, in <module>
    main(parser.parse_args())
  File "train_v2.py", line 185, in main
    img, local_labels = adversarial_img_warping(backbone=backbone,
  File "/data/work/project/ARoFace/AdvWarp.py", line 86, in adversarial_img_warping
    train_img = torch.cat((img[idx1], updated_img[idx2]), dim=0)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

**Comment by msed-Ebrahimi** [comment]
Hi, sorry for the confusion. 
In train_v2.py line 106 please comment:
> backbone._set_static_graph() 

Also, please make sure to use proper CUDA configurations.

**Comment by msed-Ebrahimi** [comment]
what is the Pytorch and CUDA version that you are using?

**Comment by deep-practice** [comment]
Besides,I can train normally on this machine using InsightFace

**Comment by msed-Ebrahimi** [comment]
> Besides,I can train normally on this machine using InsightFace

Please try the following settings:
Python 3.7
Pytorch 1.8
Cuda 11.1
